version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/sparta/project2
    overwrite: yes
jobs:
  steps:
    - name: create env file
        working-directory: ./src/
        run: |
          touch .env
          cat << EOF >> .env
          ${{ secrets.ENV }}

permissions:
  - object: /home/ubuntu
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  AfterInstall:
    - location: scripts/after-deploy.sh
      timeout: 180
      runas: ubuntu
